import { business, galleryItems, serviceCategories, team } from './data/content.js';

const root = document.querySelector('#root');
const routeNames = ['services', 'gallery', 'about'];
const path = location.pathname.replace(/\/$/, '') || '/';
const pathParts = path.split('/').filter(Boolean);
const currentRoute = routeNames.includes(pathParts.at(-1)) ? pathParts.pop() : 'home';
const basePath = pathParts.length ? `/${pathParts.join('/')}` : '';
const nav = [['Services', '/services/'], ['Gallery', '/gallery/'], ['About', '/about/']];
const page = currentRoute;
const link = (to, text, className = '') => `<a href="${basePath}${to}" class="${className}">${text}</a>`;
const image = (label = 'Image placeholder', variant = '') => `<div class="placeholder-image ${variant}" role="img" aria-label="${label}"><span>✦</span><small>${label}</small></div>`;
function navigation() { return `<nav class="navigation" aria-label="Main navigation"><div class="nav-links">${nav.map(([text, to]) => link(to, text, page === to.slice(1, -1) ? 'active' : '')).join('')}</div></nav>`; }
function footer() { return `<footer><div><strong>Company name placeholder</strong><p>Contact information placeholder</p></div><p>Social links placeholder<br>© Copyright placeholder</p></footer>`; }
function layout(content, title, eyebrow = 'Phase 1 foundation') { return `${navigation()}<main>${title ? `<header class="page-header"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${link('/', '← Return home', 'home-link')}</header>` : ''}${content}</main>${footer()}`; }
const infoCard = (index, title, text) => `<article class="info-card"><span>${index}</span><h2>${title}</h2><p>${text}</p></article>`;
function home() { return layout(`<section class="home-hero"><div class="logo-mark" aria-label="Company logo placeholder">LOGO<br><span>PLACEHOLDER</span></div><p class="eyebrow">A new home for</p><h1>${business.name}</h1><p class="hero-copy">${business.statement}</p><div class="home-actions">${nav.map(([text, to]) => link(to, `Explore ${text} <span>↗</span>`, 'arrow-link')).join('')}</div></section><section class="home-grid" aria-label="Business placeholders">${infoCard('01', 'What we do', 'A clear overview of the company’s services and approach will be added here.')}${infoCard('02', 'Business hours', business.hours)}${infoCard('03', 'Reviews', 'Reviews and testimonials placeholder — no customer quotes have been added yet.')}${infoCard('04', 'Contact', business.contact)}</section>`); }
const serviceCard = service => `<article class="service-card">${image('Service image placeholder', 'small')}<div><h3>${service.name}</h3><p>${service.description}</p></div><button type="button" disabled>Booking coming soon</button></article>`;
function services() { return layout(`<p class="page-intro">This flexible list is ready for real offerings, descriptions, images, and booking links.</p><div class="service-list">${serviceCategories.map(category => `<section class="service-category"><div class="category-heading"><p class="eyebrow">Service group</p><h2>${category.title}</h2><p>${category.intro}</p></div><div>${category.services.map(serviceCard).join('')}</div></section>`).join('')}</div>`, 'Services', 'What we offer — placeholder'); }
function gallery() { const filters = ['All work', ...new Set(galleryItems.map(item => item.service)), ...new Set(galleryItems.map(item => item.project))]; const cards = items => items.map(item => `<article class="gallery-item">${image(`Image placeholder: ${item.project}`)}<div><p>${item.service}</p><h2>${item.project}</h2><span>${item.caption}</span></div></article>`).join(''); const content = `<p class="page-intro">Filter this future gallery by service type or individual project. Each item supports an image, project name, service, and caption.</p><div class="filters" aria-label="Gallery filters">${filters.map((filter, index) => `<button data-filter="${filter}" class="${index ? '' : 'selected'}">${filter}</button>`).join('')}</div><div class="gallery-grid">${cards(galleryItems)}</div>`; queueMicrotask(() => document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach(item => item.classList.remove('selected')); button.classList.add('selected'); const filter = button.dataset.filter; document.querySelector('.gallery-grid').innerHTML = cards(filter === 'All work' ? galleryItems : galleryItems.filter(item => item.service === filter || item.project === filter)); }))); return layout(content, 'Gallery', 'Selected work — placeholders'); }
function about() { return layout(`<p class="page-intro">A balanced team layout ready for portrait photography and biographies of any length.</p><div class="team-grid">${team.map(member => `<article class="team-card">${image(`${member.name} portrait placeholder`, 'portrait')}<div><p class="eyebrow">${member.role}</p><h2>${member.name}</h2><p>${member.bio}</p></div></article>`).join('')}</div>`, 'About', 'The people behind the work'); }
root.innerHTML = page === 'services' ? services() : page === 'gallery' ? gallery() : page === 'about' ? about() : home();
